apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: budge-it

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-cluster.yaml
  - object-bucket-claim.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-route.yaml
  - backend-hpa.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-route.yaml
  - networkpolicies.yaml
  - servicemonitor.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: budge-it
