apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitops-rbac.yaml
  - image-registry.yaml
  - namespace.yaml
  - subscription.yaml
  - console-plugins.yaml
  - pipeline.yaml
  - triggers.yaml
  - eventlistener-route.yaml
  - registry-rbac.yaml
  - commit-poller.yaml
