// Package config loads all runtime configuration from environment variables.
//
// In OpenShift, DATABASE_URL comes from the Crunchy PostgresCluster user
// secret, and the BUCKET_* / AWS_* variables come from the ConfigMap and
// Secret generated by the ObjectBucketClaim (ODF / NooBaa).
package config

import (
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"
)

type Config struct {
	Port        string
	DatabaseURL string

	// SessionSecret signs login session cookies. It must be identical across
	// every backend replica (the HPA can run 2-10), so it comes from a
	// Kubernetes Secret rather than being generated per-pod.
	SessionSecret string

	// Object storage (S3-compatible, provisioned by an ObjectBucketClaim).
	BucketHost  string
	BucketPort  string
	BucketName  string
	S3AccessKey string
	S3SecretKey string
	S3UseSSL    bool
	// LocalStorageDir is a filesystem fallback used when no bucket is
	// configured (local development without ODF).
	LocalStorageDir string

	// OCR service used for PDF / image statements.
	OCREndpoint string
	OCRAPIKey   string

	MaxUploadBytes int64
	Workers        int

	// AdminEmails is the allowlist of accounts permitted to use the /admin
	// endpoints. Login is passwordless, so administrator status cannot be
	// inferred from the user record itself — it has to be granted here.
	// Empty (the default) means nobody is an administrator.
	AdminEmails []string

	// Observability links surfaced in the frontend header: the Kibana Route
	// and the budge-it dashboard inside it (see deploy/elastic).
	KibanaURL          string
	KibanaDashboardURL string

	// Version is the git commit the binary was built from, injected by main
	// from an ldflags variable (not an environment variable).
	Version string
}

func Load() (*Config, error) {
	c := &Config{
		Port:            envOr("PORT", "8080"),
		DatabaseURL:     os.Getenv("DATABASE_URL"),
		SessionSecret:   os.Getenv("SESSION_SECRET"),
		BucketHost:      os.Getenv("BUCKET_HOST"),
		BucketPort:      envOr("BUCKET_PORT", "443"),
		BucketName:      os.Getenv("BUCKET_NAME"),
		S3AccessKey:     os.Getenv("AWS_ACCESS_KEY_ID"),
		S3SecretKey:     os.Getenv("AWS_SECRET_ACCESS_KEY"),
		S3UseSSL:        envOr("BUCKET_USE_SSL", "true") == "true",
		LocalStorageDir: envOr("LOCAL_STORAGE_DIR", ""),
		OCREndpoint:     os.Getenv("OCR_ENDPOINT"),
		OCRAPIKey:       os.Getenv("OCR_API_KEY"),
		MaxUploadBytes:  envInt64("MAX_UPLOAD_BYTES", 10<<20), // 10 MB per PRD
		Workers:         int(envInt64("WORKERS", 4)),
		AdminEmails:     envList("ADMIN_EMAILS"),

		KibanaURL:          os.Getenv("KIBANA_URL"),
		KibanaDashboardURL: os.Getenv("KIBANA_DASHBOARD_URL"),
	}
	if c.DatabaseURL == "" {
		return nil, fmt.Errorf("DATABASE_URL is required")
	}
	if c.SessionSecret == "" {
		return nil, fmt.Errorf("SESSION_SECRET is required")
	}
	return c, nil
}

func (c *Config) BucketConfigured() bool {
	return c.BucketHost != "" && c.BucketName != ""
}

// IsAdmin reports whether email appears in the administrator allowlist.
// Comparison is case-insensitive because emails are stored lowercased.
func (c *Config) IsAdmin(email string) bool {
	email = strings.ToLower(strings.TrimSpace(email))
	if email == "" {
		return false
	}
	return slices.Contains(c.AdminEmails, email)
}

func (c *Config) S3Endpoint() string {
	return c.BucketHost + ":" + c.BucketPort
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

// envList splits a comma-separated variable into lowercased, trimmed entries,
// dropping empties so "a@x.com, ,b@x.com" yields two addresses.
func envList(key string) []string {
	var out []string
	for part := range strings.SplitSeq(os.Getenv(key), ",") {
		if v := strings.ToLower(strings.TrimSpace(part)); v != "" {
			out = append(out, v)
		}
	}
	return out
}

func envInt64(key string, def int64) int64 {
	if v := os.Getenv(key); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			return n
		}
	}
	return def
}
